
export { default as Test } from './src/components/test.svelte';
export { default as Test1 } from './src/components/test1.svelte';
export {default as Leaderboard} from './src/components/TournamentTemplate/Pages/ActiveTournaments/LeaderBorad.svelte';
export {default as OverView} from './src/components/TournamentTemplate/Pages/ActiveTournaments/OverView.svelte';
export {default as Support} from './src/components/TournamentTemplate/Pages/ActiveTournaments/Support.svelte';
export {default as Videos} from './src/components/TournamentTemplate/Pages/ActiveTournaments/Videos.svelte';
export {default as Section} from './src/components/TournamentTemplate/Components/Section.svelte';
export {default as Header} from './src/components/TournamentTemplate/Components/Header.svelte';
export {default as Footer} from './src/components/TournamentTemplate/Components/Footer.svelte';
export {default as ComingSoonBanner} from './src/components/TournamentTemplate/Components/ComingsoonBanner.svelte';
export {default as Devider} from './src/components/TournamentTemplate/Components/Devider.svelte';
export {default as Format} from './src/components/TournamentTemplate/Components/Format.svelte';
export {default as General} from './src/components/TournamentTemplate/Components/General.svelte';
export {default as RecentlyAnnouncedSection} from './src/components/TournamentTemplate/Components/RecentlyAnnouncedSection.svelte';
export {default as RegisterNowSection} from './src/components/TournamentTemplate/Components/RegisterNowSection.svelte';
export {default as Breadcrumb} from './src/components/TournamentTemplate/Components/Breadcrumb.svelte';
export {default as NavTavb} from './src/components/TournamentTemplate/Components/NavTabs/NavTab.svelte';
export {default as Tablink} from './src//components/TournamentTemplate/Components/NavTabs/TabLink.svelte';
export {default as BannerSection} from './src/components/TournamentTemplate/Components/Sliders/BannerSection.svelte';
export {default as CardSlider} from './src/components/TournamentTemplate/Components/Sliders/CardSlider.svelte';
export {default as FeaturedTournaments} from './src/components/TournamentTemplate/Components/Sliders/FeaturedTournaments.svelte';
export {default as HightlightsSlider} from './src/components/TournamentTemplate/Components/Sliders/HighlightsSlider.svelte';
export {default as MediaSlider} from './src/components/TournamentTemplate/Components/Sliders/MediaSlider.svelte';
export {default as PastTournaments} from './src/components/TournamentTemplate/Components/Sliders/PastTournaments.svelte';
